name: Deploy

on:
  push:
    tags:
      - v*

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'release'
  cancel-in-progress: false

env:
  NODE_VERSION: '20.4'
  NPM_REGISTRY: 'https://registry.npmjs.org'
  PNPM_VERSION: '8.6.2'

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: |
            cwd: ./
            args: [--frozen-lockfile]
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Set envs
        run: |
          export RELEASE_VERSION=${GITHUB_REF#refs/*/}
          echo "NACO_VERSION=\`$RELEASE_VERSION\`" >> $GITHUB_ENV

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './storybook-static'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-storybook
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: |
            cwd: ./
            args: [--frozen-lockfile]
          version: ${{ env.PNPM_VERSION }}

      - name: Build package
        run: pnpm build

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
