name: Quality Assurance

on:
  - push
  - pull_request

env:
  NODE_VERSION: '20.4'
  NPM_REGISTRY: 'https://registry.npmjs.org'
  PNPM_VERSION: '8.6.2'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: |
            cwd: ./
            args: [--frozen-lockfile]
          version: ${{ env.PNPM_VERSION }}

      - name: Check with svelte-check
        run: pnpm check

      - name: Check code style
        run: pnpm lint

      - name: Check library build
        run: pnpm build

      - name: Check storybook build
        run: pnpm build-storybook

      - name: Check spelling
        run: pnpm check:spelling

      - name: Run tests
        run: pnpm test
