name: Create release

env:
  PNPM_VERSION: '8.6.2'

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: Release type
        options:
          - public
          - rc
          - beta
          - alpha

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          ssh-key: ${{ secrets.RELEASER_PRIVATE_KEY }}
          fetch-depth: 0
          persist-credentials: true

      - name: Setup standard-version
        run: npm install -g standard-version

      - name: Setup GitHub Actions bot
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Create public release
        if: inputs.release_type == 'public'
        run: standard-version --infile CHANGELOG.md --same-file

      - name: Create test release
        if: inputs.release_type != 'public'
        env:
          RELEASE_SUFFIX: ${{ inputs.release_type }}
        run: standard-version --infile CHANGELOG.md -p "$RELEASE_SUFFIX" --same-file

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          ssh: true
          tags: true
